name: Docker Image CI (nextdns)

on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
      uses: docker/setup-buildx-action@v1.1.1
      with:
        # Sets up docker build command as an alias to docker buildx
        install: true
        # Switch to this builder instance
        use: true
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64/v8 --file nextdns/docker/Dockerfile --tag nextdns-udm:latest nextdns/docker
